"""Transition schema constants for v3 hourly mimic-code pipeline."""

from __future__ import annotations

REQUIRED_TRANSITION_V3_COLUMNS = [
    "episode_id",
    "episode_step",
    "transition_id",
    "patient_id",
    "index_hadm_id",
    "t",
    "index_admittime",
    "index_dischtime",
    "y_t1",
    "done",
    "a_t",
    "a_t_vaso",
    "a_t_vent",
    "a_t_crrt",
    "a_t_source",
    "a_t_raw_discharge_location",
    "s_t_sofa",
    "s_t_mbp",
    "s_t_heart_rate",
    "s_t_resp_rate",
    "s_t_spo2",
    "s_t_creatinine",
    "s_t_bun",
    "s_t_age",
    "s_t_charlson",
    "s_t1_sofa",
    "s_t1_mbp",
    "s_t1_heart_rate",
    "s_t1_resp_rate",
    "s_t1_spo2",
    "s_t1_creatinine",
    "s_t1_bun",
    "s_t1_age",
    "s_t1_charlson",
    "split",
    "sample_tag",
    "source_dataset",
    "schema_version",
    "build_timestamp_utc",
]

